name: refectory
description: The refectory communal dinning hall app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  # flutter_svg: ^0.18.0

  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.12.9+5

  google_sign_in: 4.5.1
  apple_sign_in: 0.1.0

  font_awesome_flutter: 8.8.1
  provider: 4.0.5

  uuid: 2.2.0

  table_calendar: ^2.2.3

  sliding_up_panel: ^1.0.2
  smooth_star_rating: 1.1.1
  dash_chat: 1.1.14
  qr_code_scanner: ^0.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - assets/images/